export interface DocumentCardProps {
  name: string;
  description: string;
  category: string | undefined;
  url: string;
}

export const documentsArray: DocumentCardProps[] = [
  { name: "CNH", description: "Carteira de habilitação!", category: "declarações", url: "https://meudocumento.com.br/cnh" },
  { name: "RG", description: "Documento de identidade!", category: "faturas", url: "https://meudocumento.com.br/rg" },
  { name: "CPF", description: "Cadastro de pessoa física!", category: "contratos", url: "https://meudocumento.com.br/cpf" },
  { name: "Passaporte", description: "Documento para viagens!", category: "boletos", url: "https://meudocumento.com.br/passaporte" },
  { name: "Título de Eleitor", description: "Documento eleitoral!", category: "comprovantes", url: "https://meudocumento.com.br/título-de-eleitor" },
  { name: "CRLV", description: "Licenciamento veicular!", category: "licenças", url: "https://meudocumento.com.br/crlv" },
  { name: "Carteira de Trabalho", description: "Registro profissional!", category: "certidões", url: "https://meudocumento.com.br/carteira-de-trabalho" },
  { name: "Certidão de Nascimento", description: "Registro de nascimento!", category: "declarações", url: "https://meudocumento.com.br/certidão-de-nascimento" },
  { name: "Certidão de Casamento", description: "Registro de casamento!", category: "faturas", url: "https://meudocumento.com.br/certidão-de-casamento" },
  { name: "Contrato de Aluguel", description: "Locação de imóvel!", category: "faturas", url: "https://meudocumento.com.br/contrato-de-aluguel" },
  { name: "Contrato de Compra", description: "Aquisição de bem!", category: "certidões", url: "https://meudocumento.com.br/contrato-de-compra" },
  { name: "Boleto de Luz", description: "Conta de energia!", category: "licenças", url: "https://meudocumento.com.br/boleto-de-luz" },
  { name: "Boleto de Água", description: "Conta de água!", category: "contratos", url: "https://meudocumento.com.br/boleto-de-água" },
  { name: "Fatura do Cartão", description: "Cobrança mensal!", category: "declarações", url: "https://meudocumento.com.br/fatura-do-cartão" },
  { name: "Fatura de Celular", description: "Conta telefônica!", category: "contratos", url: "https://meudocumento.com.br/fatura-de-celular" },
  { name: "Comprovante de Residência", description: "Endereço atualizado!", category: "comprovantes", url: "https://meudocumento.com.br/comprovante-de-residência" },
  { name: "Comprovante de Renda", description: "Prova de ganhos!", category: "faturas", url: "https://meudocumento.com.br/comprovante-de-renda" },
  { name: "Licença Médica", description: "Dispensa por saúde!", category: "faturas", url: "https://meudocumento.com.br/licença-médica" },
  { name: "Licença de Funcionamento", description: "Autorização comercial!", category: "registros", url: "https://meudocumento.com.br/licença-de-funcionamento" },
  { name: "Declaração de Imposto", description: "IRPF anual!", category: "boletos", url: "https://meudocumento.com.br/declaração-de-imposto" },
  { name: "Declaração Escolar", description: "Confirmação de matrícula!", category: "documentos", url: "https://meudocumento.com.br/declaração-escolar" },
  { name: "Registro de Imóvel", description: "Posse do imóvel!", category: "contratos", url: "https://meudocumento.com.br/registro-de-imóvel" },
  { name: "Registro de Veículo", description: "Propriedade veicular!", category: "licenças", url: "https://meudocumento.com.br/registro-de-veículo" },
  { name: "A 1", description: "Delectus amet praesentium", category: "faturas", url: "https://meudocumento.com.br/a-1" },
  { name: "O 2", description: "Veniam nobis vel", category: "certidões", url: "https://meudocumento.com.br/o-2" },
  { name: "A 3", description: "Ipsam hic voluptatem at", category: "boletos", url: "https://meudocumento.com.br/a-3" },
  { name: "A 4", description: "Occaecati aliquam delectus", category: "contratos", url: "https://meudocumento.com.br/a-4" },
  { name: "O 5", description: "Occaecati tempore nam a", category: "licenças", url: "https://meudocumento.com.br/o-5" },
  { name: "A 6", description: "Harum vel harum temporibus", category: "declarações", url: "https://meudocumento.com.br/a-6" },
  { name: "A 7", description: "Amet quibusdam assumenda", category: "certidões", url: "https://meudocumento.com.br/a-7" },
  { name: "O 8", description: "Unde praesentium harum magni", category: "faturas", url: "https://meudocumento.com.br/o-8" },
  { name: "A 9", description: "Eius hic nisi voluptatem id", category: "documentos", url: "https://meudocumento.com.br/a-9" },
  { name: "A 10", description: "Et molestiae alias vero", category: "boletos", url: "https://meudocumento.com.br/a-10" },
  { name: "O 11", description: "Inventore animi ea", category: "registros", url: "https://meudocumento.com.br/o-11" },
  { name: "O 12", description: "Dolor sit possimus", category: "contratos", url: "https://meudocumento.com.br/o-12" },
  { name: "A 13", description: "Optio ratione rem ut", category: "boletos", url: "https://meudocumento.com.br/a-13" },
  { name: "A 14", description: "Facilis autem tempore", category: "registros", url: "https://meudocumento.com.br/a-14" },
  { name: "O 15", description: "Necessitatibus ipsa sed", category: "declarações", url: "https://meudocumento.com.br/o-15" },
  { name: "O 16", description: "Ipsam ab esse debitis iste", category: "documentos", url: "https://meudocumento.com.br/o-16" },
  { name: "A 17", description: "Deserunt similique accusamus", category: "declarações", url: "https://meudocumento.com.br/a-17" },
  { name: "A 18", description: "Vel odit inventore quo eaque", category: "licenças", url: "https://meudocumento.com.br/a-18" },
  { name: "A 19", description: "Esse dolor ab similique", category: "boletos", url: "https://meudocumento.com.br/a-19" },
  { name: "O 20", description: "Tempore non veritatis", category: "certidões", url: "https://meudocumento.com.br/o-20" },
  { name: "A 21", description: "Dolor in odit quo", category: "registros", url: "https://meudocumento.com.br/a-21" },
  { name: "O 22", description: "Placeat inventore sunt", category: "declarações", url: "https://meudocumento.com.br/o-22" },
  { name: "A 23", description: "Error illo cumque labore", category: "certidões", url: "https://meudocumento.com.br/a-23" },
  { name: "O 24", description: "Rerum a eum reiciendis", category: "registros", url: "https://meudocumento.com.br/o-24" },
  { name: "A 25", description: "Nobis fugit a aliquam", category: "boletos", url: "https://meudocumento.com.br/a-25" },
  { name: "O 26", description: "At et deserunt magnam soluta", category: "faturas", url: "https://meudocumento.com.br/o-26" },
  { name: "A 27", description: "At quaerat est hic", category: "contratos", url: "https://meudocumento.com.br/a-27" },
  { name: "O 28", description: "Nulla officia vero fuga", category: "certidões", url: "https://meudocumento.com.br/o-28" },
  { name: "A 29", description: "Possimus reiciendis tempora", category: "declarações", url: "https://meudocumento.com.br/a-29" },
  { name: "A 30", description: "Alias voluptate impedit", category: "registros", url: "https://meudocumento.com.br/a-30" },
  { name: "A 31", description: "Soluta amet at", category: "certidões", url: "https://meudocumento.com.br/a-31" },
  { name: "A 32", description: "Voluptas autem sit mollitia", category: "faturas", url: "https://meudocumento.com.br/a-32" },
  { name: "O 33", description: "Saepe quae natus unde et", category: "documentos", url: "https://meudocumento.com.br/o-33" },
  { name: "O 34", description: "Tempore vel libero ab", category: "documentos", url: "https://meudocumento.com.br/o-34" },
  { name: "A 35", description: "Assumenda optio in provident", category: "documentos", url: "https://meudocumento.com.br/a-35" },
  { name: "A 36", description: "Modi hic repudiandae unde", category: "registros", url: "https://meudocumento.com.br/a-36" },
  { name: "O 37", description: "Mollitia sint mollitia", category: "boletos", url: "https://meudocumento.com.br/o-37" },
  { name: "O 38", description: "Rem sed porro nulla", category: "registros", url: "https://meudocumento.com.br/o-38" },
  { name: "A 39", description: "Sunt dolore recusandae non", category: "declarações", url: "https://meudocumento.com.br/a-39" },
  { name: "A 40", description: "Ea ad ut blanditiis", category: "faturas", url: "https://meudocumento.com.br/a-40" },
  { name: "A 41", description: "Vel ex libero", category: "contratos", url: "https://meudocumento.com.br/a-41" },
  { name: "A 42", description: "Veritatis tenetur odit", category: "licenças", url: "https://meudocumento.com.br/a-42" },
  { name: "O 43", description: "Accusamus eius nostrum iusto", category: "documentos", url: "https://meudocumento.com.br/o-43" },
  { name: "A 44", description: "Explicabo ullam in molestias", category: "boletos", url: "https://meudocumento.com.br/a-44" },
  { name: "A 45", description: "Quod esse optio incidunt", category: "boletos", url: "https://meudocumento.com.br/a-45" },
  { name: "A 46", description: "Tenetur harum ipsum", category: "registros", url: "https://meudocumento.com.br/a-46" },
  { name: "O 47", description: "Libero sed quia debitis", category: "contratos", url: "https://meudocumento.com.br/o-47" },
  { name: "O 48", description: "Temporibus non natus nostrum", category: "documentos", url: "https://meudocumento.com.br/o-48" },
  { name: "O 49", description: "Non natus delectus eligendi", category: "faturas", url: "https://meudocumento.com.br/o-49" },
  { name: "A 50", description: "Nihil animi blanditiis id", category: "contratos", url: "https://meudocumento.com.br/a-50" },
  { name: "A 51", description: "Non hic libero maiores", category: "contratos", url: "https://meudocumento.com.br/a-51" },
  { name: "O 52", description: "Modi laborum voluptate autem", category: "boletos", url: "https://meudocumento.com.br/o-52" },
  { name: "A 53", description: "Asperiores possimus eius", category: "registros", url: "https://meudocumento.com.br/a-53" },
  { name: "A 54", description: "At ad recusandae dolorem", category: "contratos", url: "https://meudocumento.com.br/a-54" },
  { name: "A 55", description: "Optio eos neque", category: "certidões", url: "https://meudocumento.com.br/a-55" },
  { name: "O 56", description: "Officiis rerum tempore", category: "declarações", url: "https://meudocumento.com.br/o-56" },
  { name: "A 57", description: "Velit nobis laboriosam", category: "certidões", url: "https://meudocumento.com.br/a-57" },
  { name: "O 58", description: "Fugiat alias commodi", category: "comprovantes", url: "https://meudocumento.com.br/o-58" },
  { name: "O 59", description: "Dolores ipsum veniam nemo", category: "faturas", url: "https://meudocumento.com.br/o-59" },
  { name: "A 60", description: "Dicta quas laboriosam", category: "comprovantes", url: "https://meudocumento.com.br/a-60" },
  { name: "A 61", description: "Porro vitae officiis", category: "faturas", url: "https://meudocumento.com.br/a-61" },
  { name: "A 62", description: "Illo laborum autem similique", category: "documentos", url: "https://meudocumento.com.br/a-62" },
  { name: "A 63", description: "Aliquam reprehenderit eius a", category: "boletos", url: "https://meudocumento.com.br/a-63" },
  { name: "A 64", description: "Eum eum nisi ipsam amet quis", category: "contratos", url: "https://meudocumento.com.br/a-64" },
  { name: "A 65", description: "Nemo quo enim aliquam", category: "registros", url: "https://meudocumento.com.br/a-65" },
  { name: "O 66", description: "Autem unde inventore nemo", category: "contratos", url: "https://meudocumento.com.br/o-66" },
  { name: "A 67", description: "Aut quia ducimus magnam", category: "certidões", url: "https://meudocumento.com.br/a-67" },
  { name: "O 68", description: "Exercitationem nihil illo id", category: "certidões", url: "https://meudocumento.com.br/o-68" },
  { name: "O 69", description: "Odio facere enim beatae", category: "declarações", url: "https://meudocumento.com.br/o-69" },
  { name: "A 70", description: "Sit saepe numquam iure ut", category: "contratos", url: "https://meudocumento.com.br/a-70" },
  { name: "O 71", description: "Earum nisi commodi dolores", category: "licenças", url: "https://meudocumento.com.br/o-71" },
  { name: "A 72", description: "Amet quaerat quisquam sequi", category: "certidões", url: "https://meudocumento.com.br/a-72" },
  { name: "A 73", description: "Dignissimos ullam hic", category: "declarações", url: "https://meudocumento.com.br/a-73" },
  { name: "A 74", description: "Quam veritatis cumque", category: "comprovantes", url: "https://meudocumento.com.br/a-74" },
  { name: "A 75", description: "Inventore adipisci voluptate", category: "contratos", url: "https://meudocumento.com.br/a-75" },
  { name: "O 76", description: "Repudiandae ut nobis", category: "contratos", url: "https://meudocumento.com.br/o-76" },
  { name: "A 77", description: "Nesciunt maxime at quaerat", category: "declarações", url: "https://meudocumento.com.br/a-77" },
];
